services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_processor
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.infra/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  image-processor:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgres://postgres:postgres@db:5432/image_processor?sslmode=disable"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
